kind: LocalStorage
apiVersion: storage.caoyingjunz.io/v1
metadata:
  annotations:
    # 自定义可分配的存储容量
    volume.caoyingjunz.io/node-size: 360Gi
  name: test-ls
spec:
  volumeGroup: test-vg
  node: test-node
  disks:
    - name: test-disk
      identifier: test-identifier
