apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: localstorage.caoyingjunz.io
mountOptions:
  - key1=caoyingjunz
parameters:
  project: pixiu
provisioner: localstorage.csi.caoyingjunz.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
