apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixiu-localstorage-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixiu-ls-controller
  template:
    metadata:
      labels:
        app: pixiu-ls-controller
    spec:
      serviceAccountName: csi-ls-node-sa
      containers:
        - args:
            - -v=2
          image: pixiuio/localstorage-controller:latest
          imagePullPolicy: Always
          name: ls-controller
      dnsPolicy: Default
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always

