apiVersion: apps/v1
kind: Deployment
metadata:
  name: pixiu-localstorage-controller
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pixiu-ls-controller
  template:
    metadata:
      labels:
        app: pixiu-ls-controller
    spec:
      serviceAccountName: csi-ls-node-sa
      containers:
        - args:
            - -v=2
            # port's value equals 0 means health check func disabled
            - --healthz-port=10258
          image: pixiuio/localstorage-controller:latest
          imagePullPolicy: Always
          name: ls-controller
          ports:
            - containerPort: 10258
              name: healthz
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            failureThreshold: 5
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 5
      dnsPolicy: Default
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: Always

