apiVersion: v1
kind: Pod
metadata:
  name: ls-scheduler-extender
  namespace: kube-system
  labels:
    app: ls-scheduler-extender
spec:
  serviceAccountName: csi-ls-node-sa
  containers:
    - args:
        - -v=2
        - --port=8090
      image: harbor.powerlaw.club/pixiuio/scheduler-extender:latest
      imagePullPolicy: Always
      name: ls-scheduler-extender
      livenessProbe:
        httpGet:
          path: /version
          port: 8090
        initialDelaySeconds: 5
        timeoutSeconds: 30
  dnsPolicy: Default
  nodeSelector:
    kubernetes.io/os: linux
  restartPolicy: Always
