apiVersion: v1
kind: Pod
metadata:
  name: ls-scheduler-extender
  namespace: kube-system
  labels:
    app: ls-scheduler-extender
spec:
  containers:
    - args:
        - -v=2
        - --port=8090
      image: harbor.powerlaw.club/pixiuio/scheduler-extender:latest
      imagePullPolicy: Always
      name: ls-scheduler-extender
      volumeMounts:
        - name: kube-data
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount/token
          subPath: token
        - name: kube-data
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          subPath: ca.crt
  volumes:
    - name: kube-data
      hostPath:
        path: /data
