apiVersion: apps.pixiu.io/v1alpha1
kind: AdvancedImage
metadata:
  name: sample-ai
spec:
  parallels: 2
  imageNodes: 6
  progressDelaySeconds: 300
  selector:
    matchLabels:
      key: value
  template:
    spec:
      image: nginx
      action: pull
      imagePullPolicy: ifNotPresent
      selector:
        nodes:
          - node1
