name: Docker Pipeline

on:
  push:
    branches:
      - master

jobs:

  golang-lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}

    - name: Build the pixiu binariy
      run: go build -v ./...
    - name: Run pixiu unit test
      run: go test -v ./...
