name: Generate api clients

on:
  pull_request:
    branches:
      - master

env:
  GO_VERSION: '1.17.3'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: generate api clients
        run: make client-gen
